// apps/web/src/lib/site/demos/data-mosh/react/runtime.tsx
import { useEffect, useRef } from 'react';
import { useFrame } from 'spektral/react';
import { createOriginCleanVideo, type OriginCleanVideo } from './video-source';

/**
 * Streams decoded video frames into the Data Mosh material with CORS-safe settings.
 */
export default function Runtime() {
	const videoHandleRef = useRef<OriginCleanVideo | null>(null);
	const lastVideoTime = useRef(0);
	const resetNextFrame = useRef(true);

	useEffect(() => {
		const handle = createOriginCleanVideo();
		videoHandleRef.current = handle;
		void handle.ready.catch((error) => console.error('[Data Mosh] Unable to load video.', error));

		return () => {
			handle.dispose();
			if (videoHandleRef.current === handle) videoHandleRef.current = null;
		};
	}, []);

	useFrame((frame) => {
		const video = videoHandleRef.current?.video;
		if (!video || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA) return;

		const looped = video.currentTime + 0.25 < lastVideoTime.current;
		frame.setUniform('uReset', resetNextFrame.current || looped || video.seeking ? 1 : 0);
		frame.setTexture('video', {
			source: video,
			update: 'perFrame',
			flipY: true,
			colorSpace: 'srgb'
		});
		lastVideoTime.current = video.currentTime;
		resetNextFrame.current = false;
	});

	return null;
}

// apps/web/src/lib/site/demos/data-mosh/vue/runtime.vue
<script setup lang="ts">
import { onMounted, onUnmounted } from 'vue';
import { useFrame } from 'spektral/vue';
import { createOriginCleanVideo, type OriginCleanVideo } from './video-source';

let videoHandle: OriginCleanVideo | null = null;
let lastVideoTime = 0;
let resetNextFrame = true;

onMounted(() => {
	const handle = createOriginCleanVideo();
	videoHandle = handle;
	void handle.ready.catch((error) => console.error('[Data Mosh] Unable to load video.', error));
});

onUnmounted(() => {
	videoHandle?.dispose();
	videoHandle = null;
});

useFrame((frame) => {
	const video = videoHandle?.video;
	if (!video || video.readyState < HTMLMediaElement.HAVE_CURRENT_DATA) return;

	const looped = video.currentTime + 0.25 < lastVideoTime;
	frame.setUniform('uReset', resetNextFrame || looped || video.seeking ? 1 : 0);
	frame.setTexture('video', {
		source: video,
		update: 'perFrame',
		flipY: true,
		colorSpace: 'srgb'
	});
	lastVideoTime = video.currentTime;
	resetNextFrame = false;
});
</script>
